# Generated by Django 4.2.27 on 2026-04-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_simplify_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='matricula',
            field=models.CharField(help_text='Número de matrícula profesional', max_length=100, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del médico', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AddIndex(
            model_name='medico',
            index=models.Index(fields=['matricula'], name='medicos_med_matricu_07aab0_idx'),
        ),
        migrations.AddIndex(
            model_name='medico',
            index=models.Index(fields=['nombre'], name='medicos_med_nombre_84e00c_idx'),
        ),
    ]
