# Generated by Django 4.2.27 on 2026-04-24 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicos', '0003_alter_medico_matricula_alter_medico_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario de Django asociado a este médico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medico', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
    ]
