# Generated by Django 4.2.27 on 2026-04-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paciente",
            options={
                "ordering": ["apellido", "nombre"],
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
            },
        ),
        migrations.AlterField(
            model_name="paciente",
            name="apellido",
            field=models.CharField(max_length=30, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Correo electrónico del paciente",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="fecha_nacimiento",
            field=models.DateField(verbose_name="Fecha de Nacimiento"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="iden",
            field=models.CharField(
                help_text="Número de documento de identidad del paciente",
                max_length=15,
                unique=True,
                verbose_name="Identificación",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nombre",
            field=models.CharField(max_length=30, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="observaciones",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notas adicionales sobre el paciente",
                verbose_name="Observaciones",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="sexo",
            field=models.CharField(
                choices=[
                    ("Masculino", "Masculino"),
                    ("Femenino", "Femenino"),
                    ("Sin asignar", "Sin asignar"),
                ],
                default="Sin asignar",
                max_length=15,
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefono",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número de teléfono de contacto",
                max_length=50,
                verbose_name="Teléfono",
            ),
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(fields=["iden"], name="pacientes_p_iden_413cda_idx"),
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(
                fields=["apellido", "nombre"], name="pacientes_p_apellid_72499c_idx"
            ),
        ),
    ]
