# Generated by Django 4.2.27 on 2026-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_options_alter_paciente_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo_iden',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CI', 'Ci'), ('LC', 'LC'), ('LE', 'LE'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro'), ('PRO', 'PRO')], default='DNI', help_text='Tipo de documento de identidad del paciente', max_length=15, verbose_name='Tipo de Identificación'),
        ),
    ]
