# Generated by Django 4.2.27 on 2026-05-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_tipo_iden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='iden',
            field=models.CharField(help_text='Número de documento de identidad del paciente', max_length=15, verbose_name='Identificación'),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('tipo_iden', 'iden')},
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['tipo_iden', 'iden'], name='pacientes_p_tipo_id_463290_idx'),
        ),
    ]
