# Generated by Django 4.2.27 on 2026-05-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_iden_alter_paciente_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tipo_iden',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CI', 'Ci'), ('LC', 'LC'), ('LE', 'LE'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro'), ('PRO', 'PRO'), ('NEO', 'NEO'), ('NN', 'NN')], default='DNI', help_text='Tipo de documento de identidad del paciente', max_length=15, verbose_name='Tipo de Identificación'),
        ),
    ]
