# Generated by Django 4.2.27 on 2026-05-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_tipo_iden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='iden',
            field=models.CharField(help_text='Número de documento de identidad del paciente', max_length=25, verbose_name='Identificación'),
        ),
    ]
