# Generated by Django 4.2.27 on 2026-05-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_fix_email_null_to_empty_string'),
        ('pacientes', '0006_alter_paciente_iden_max_length'),
    ]

    operations = [
    ]
