# Generated by Django 4.2.27 on 2026-02-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.IntegerField(verbose_name='Número de Orden')),
                ('numero_protocolo', models.CharField(max_length=50, verbose_name='Número de Protocolo')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Archivo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error en el envío')], default='PENDIENTE', max_length=20, verbose_name='Estado del Informe')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('email_destino', models.EmailField(blank=True, max_length=254, verbose_name='Email de Destino')),
                ('intentos_envio', models.IntegerField(default=0, verbose_name='Intentos de Envío')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('id_turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turnos.turno', verbose_name='Turno')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('paciente', 'numero_orden', 'numero_protocolo')},
            },
        ),
    ]
