# Generated by Django 4.2.27 on 2026-02-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informes',
            name='whatsapp_enviado',
            field=models.BooleanField(default=False, verbose_name='WhatsApp Enviado'),
        ),
        migrations.AddField(
            model_name='informes',
            name='whatsapp_error',
            field=models.TextField(blank=True, verbose_name='Error WhatsApp'),
        ),
        migrations.AddField(
            model_name='informes',
            name='whatsapp_telefono',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono WhatsApp Destino'),
        ),
    ]
