# Generated by Django 4.2.27 on 2026-04-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_options_alter_paciente_apellido_and_more'),
        ('turnos', '0005_alter_agenda_options_alter_cupo_options_and_more'),
        ('informes', '0002_informes_whatsapp_enviado_informes_whatsapp_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informes',
            name='email_destino',
            field=models.EmailField(blank=True, default='', help_text='Dirección de correo del paciente', max_length=254, verbose_name='Email de Destino'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error en el envío')], db_index=True, default='PENDIENTE', max_length=20, verbose_name='Estado del Informe'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se envió el informe', null=True, verbose_name='Fecha de Envío'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='id_turno',
            field=models.ForeignKey(blank=True, help_text='Turno asociado al informe', null=True, on_delete=django.db.models.deletion.PROTECT, to='turnos.turno', verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='intentos_envio',
            field=models.PositiveSmallIntegerField(default=0, help_text='Número de veces que se intentó enviar el informe', verbose_name='Intentos de Envío'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='mensaje_error',
            field=models.TextField(blank=True, default='', help_text='Detalle del error en caso de fallo', verbose_name='Mensaje de Error'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='nombre_archivo',
            field=models.CharField(blank=True, default='', help_text='Nombre del archivo PDF generado', max_length=255, verbose_name='Nombre del Archivo'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='numero_orden',
            field=models.IntegerField(help_text='Número de petición del informe', verbose_name='Número de Orden'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='numero_protocolo',
            field=models.CharField(help_text='Número de protocolo o turno', max_length=50, verbose_name='Número de Protocolo'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='whatsapp_enviado',
            field=models.BooleanField(default=False, help_text='Indica si se envió por WhatsApp exitosamente', verbose_name='WhatsApp Enviado'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='whatsapp_error',
            field=models.TextField(blank=True, default='', help_text='Detalle del error en envío por WhatsApp', verbose_name='Error WhatsApp'),
        ),
        migrations.AlterField(
            model_name='informes',
            name='whatsapp_telefono',
            field=models.CharField(blank=True, default='', help_text='Número de teléfono para WhatsApp', max_length=30, verbose_name='Teléfono WhatsApp Destino'),
        ),
        migrations.AddIndex(
            model_name='informes',
            index=models.Index(fields=['-fecha_creacion'], name='informes_in_fecha_c_4f7f60_idx'),
        ),
        migrations.AddIndex(
            model_name='informes',
            index=models.Index(fields=['estado'], name='informes_in_estado_3d7c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='informes',
            index=models.Index(fields=['paciente', 'numero_orden'], name='informes_in_pacient_800bad_idx'),
        ),
    ]
