# Generated by Django 4.2.27 on 2026-05-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_alter_informes_email_destino_alter_informes_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informes',
            name='whatsapp_error',
            field=models.TextField(blank=True, default='', help_text='Detalle del error en envío por WhatsApp', verbose_name='Error WhatsApp'),
        ),
    ]
