# Generated by Django 4.2.27 on 2026-01-28 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('medicos', '0002_simplify_medico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('color', models.CharField(default='#00d4ff', help_text='Color HEX para el calendario (ej. #00d4ff)', max_length=7)),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('determinaciones', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('nota_interna', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='turnos.agenda')),
                ('dni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='pacientes.paciente')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='medicos.medico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'creado'],
            },
        ),
        migrations.CreateModel(
            name='Coordinados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turno', models.IntegerField(unique=True, verbose_name='ID del Turno')),
                ('fecha_coordinacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Coordinación')),
                ('determinaciones', models.TextField(blank=True, verbose_name='Determinaciones')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente', verbose_name='Paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que coordinó')),
            ],
            options={
                'verbose_name': 'Turno Coordinado',
                'verbose_name_plural': 'Turnos Coordinados',
                'ordering': ['-fecha_coordinacion'],
            },
        ),
        migrations.CreateModel(
            name='Cupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_total', models.PositiveIntegerField()),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='turnos.agenda')),
            ],
            options={
                'unique_together': {('agenda', 'fecha')},
            },
        ),
    ]
