# Generated by Django 4.2.27 on 2026-03-18 16:05

from django.db import migrations


def actualizar_colores_agendas(apps, schema_editor):
    """
    Actualiza los colores de las agendas principales con la paleta unificada.

    Paleta de colores:
    - Ambulatorio: #B2D5BA (menta)
    - Curvas: #EFF3CD (crema)
    - Emergencia: #61ADA0 (teal medio)
    """
    Agenda = apps.get_model("turnos", "Agenda")

    # Mapeo de slugs a colores
    colores_actualizados = {
        "ambulatorio": "#B2D5BA",
        "curvas": "#EFF3CD",
        "emergencia": "#61ADA0",
    }

    # Actualizar cada agenda
    for slug, color in colores_actualizados.items():
        try:
            agenda = Agenda.objects.get(slug=slug)
            agenda.color = color
            agenda.save(update_fields=["color"])
            print(f"✓ Agenda '{agenda.name}' actualizada con color {color}")
        except Agenda.DoesNotExist:
            print(f"⚠ Agenda con slug '{slug}' no encontrada, omitiendo...")


def revertir_colores_agendas(apps, schema_editor):
    """
    Revierte los colores a valores por defecto (en caso de rollback).
    """
    Agenda = apps.get_model("turnos", "Agenda")

    # Colores por defecto
    color_default = "#00d4ff"

    for slug in ["ambulatorio", "curvas", "emergencia"]:
        try:
            agenda = Agenda.objects.get(slug=slug)
            agenda.color = color_default
            agenda.save(update_fields=["color"])
            print(f"↩ Agenda '{agenda.name}' revertida a color por defecto")
        except Agenda.DoesNotExist:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("turnos", "0002_fix_turno_dni_nullable"),
    ]

    operations = [
        migrations.RunPython(actualizar_colores_agendas, revertir_colores_agendas),
    ]
