# Generated by Django 4.2.27 on 2026-04-21 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_alter_medico_matricula_alter_medico_nombre_and_more'),
        ('pacientes', '0002_alter_paciente_options_alter_paciente_apellido_and_more'),
        ('instituciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos', '0004_actualizar_color_pediatricos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['name'], 'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.AlterModelOptions(
            name='cupo',
            options={'ordering': ['fecha', 'agenda'], 'verbose_name': 'Cupo', 'verbose_name_plural': 'Cupos'},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', 'creado'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='coordinados',
            name='institucion',
            field=models.ForeignKey(blank=True, help_text='Institucion de origen de la orden medica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinados', to='instituciones.institucion', verbose_name='Institucion'),
        ),
        migrations.AddField(
            model_name='turno',
            name='institucion',
            field=models.ForeignKey(blank=True, help_text='Institucion de origen de la orden medica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='instituciones.institucion', verbose_name='Institucion'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='color',
            field=models.CharField(default='#00d4ff', help_text='Color HEX para el calendario (ej. #00d4ff)', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='name',
            field=models.CharField(help_text='Nombre de la agenda o servicio', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='slug',
            field=models.SlugField(help_text='Identificador único para URLs (ej: ambulatorio, curvas)', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='usuario',
            field=models.CharField(blank=True, default='', help_text='Usuario que creó o gestiona esta agenda', max_length=150, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='coordinados',
            name='determinaciones',
            field=models.TextField(blank=True, default='', help_text='Lista de estudios coordinados', verbose_name='Determinaciones'),
        ),
        migrations.AlterField(
            model_name='coordinados',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Coordinó'),
        ),
        migrations.AlterField(
            model_name='cupo',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='turnos.agenda', verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='cupo',
            name='cantidad_total',
            field=models.PositiveIntegerField(help_text='Número total de turnos disponibles para esta fecha', verbose_name='Cantidad Total'),
        ),
        migrations.AlterField(
            model_name='cupo',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cupo',
            name='usuario',
            field=models.CharField(blank=True, default='', help_text='Usuario que creó este cupo', max_length=150, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='feriados',
            name='descripcion',
            field=models.CharField(blank=True, default='', help_text='Descripción del feriado (ej: Día de la Independencia)', max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='feriados',
            name='fecha',
            field=models.DateField(help_text='Fecha del feriado', unique=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='feriados',
            name='usuario',
            field=models.CharField(blank=True, default='', help_text='Usuario que registró el feriado', max_length=150, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='turnos.agenda', verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='determinaciones',
            field=models.TextField(blank=True, default='', help_text='Lista de análisis o estudios solicitados', verbose_name='Determinaciones'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='dni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del Turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='medicos.medico', verbose_name='Médico Solicitante'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nota_interna',
            field=models.TextField(blank=True, default='', help_text='Observaciones internas del turno', verbose_name='Nota Interna'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Creó el Turno'),
        ),
        migrations.AddIndex(
            model_name='coordinados',
            index=models.Index(fields=['id_turno'], name='turnos_coor_id_turn_02cd36_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinados',
            index=models.Index(fields=['-fecha_coordinacion'], name='turnos_coor_fecha_c_cf611f_idx'),
        ),
        migrations.AddIndex(
            model_name='cupo',
            index=models.Index(fields=['fecha', 'agenda'], name='turnos_cupo_fecha_8d7c73_idx'),
        ),
        migrations.AddIndex(
            model_name='feriados',
            index=models.Index(fields=['fecha'], name='turnos_feri_fecha_94abcd_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['fecha', 'agenda'], name='turnos_turn_fecha_41495a_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['dni'], name='turnos_turn_dni_id_9052a5_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['creado'], name='turnos_turn_creado_2c34ce_idx'),
        ),
    ]
