# Generated by Django 5.2.9 on 2025-12-04 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_capacidaddia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('color', models.CharField(default='#00d4ff', help_text='Color HEX para el calendario (ej. #00d4ff)', max_length=7)),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
        migrations.AlterField(
            model_name='capacidaddia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cupo',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='capacidaddia',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='turnos.agenda'),
        ),
        migrations.AddField(
            model_name='cupo',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupos', to='turnos.agenda'),
        ),
        migrations.AddField(
            model_name='turno',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='turnos.agenda'),
        ),
        migrations.AlterUniqueTogether(
            name='capacidaddia',
            unique_together={('agenda', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='cupo',
            unique_together={('agenda', 'fecha')},
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('capacidad', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='turnos.agenda')),
            ],
            options={
                'unique_together': {('agenda', 'weekday')},
            },
        ),
    ]
