# Generated by Django 5.2.9 on 2025-12-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_create_default_agendas'),
        ('turnos', '0004_create_default_weeklyavailability'),
    ]

    operations = [
    ]
