# Generated by Django 4.2.27 on 2026-05-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_agregar_estado_turno_y_related_name'),
        ('turnos', '0005_alter_agenda_options_alter_cupo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='ordenes',
            field=models.ManyToManyField(blank=True, help_text='Órdenes de laboratorio vinculadas a este turno', related_name='turnos', to='ordenes.ordenlaboratorio', verbose_name='Órdenes de Laboratorio'),
        ),
    ]
