# Generated by Django 4.2.27 on 2026-05-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_coordinados_campos_hl7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinados',
            name='ack_estado',
            field=models.CharField(blank=True, choices=[('AA', 'Aceptado (AA)'), ('AE', 'Error de Aplicación (AE)'), ('AR', 'Rechazado (AR)')], default='', help_text='AA=Aceptado, AE=Error, AR=Rechazado', max_length=2, verbose_name='Estado ACK'),
        ),
        migrations.AlterField(
            model_name='coordinados',
            name='ack_recibido',
            field=models.TextField(blank=True, default='', help_text='Contenido ER7 del ACK recibido del LIS', verbose_name='ACK recibido'),
        ),
        migrations.AlterField(
            model_name='coordinados',
            name='mensaje_hl7',
            field=models.TextField(blank=True, default='', help_text='Contenido del mensaje OML^O21 enviado al LIS', verbose_name='Mensaje HL7'),
        ),
        migrations.AlterField(
            model_name='coordinados',
            name='mensaje_tipo',
            field=models.CharField(choices=[('ASTM', 'ASTM (legacy)'), ('HL7', 'HL7 v2.5')], default='HL7', help_text='HL7 o ASTM según el protocolo utilizado para coordinar', max_length=10, verbose_name='Tipo de mensaje'),
        ),
    ]
