# Generated by Django 5.2.9 on 2025-12-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_make_agenda_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyavailability',
            name='desde_fecha',
            field=models.DateField(blank=True, help_text='Fecha desde la cual aplicar esta disponibilidad (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='weeklyavailability',
            name='hasta_fecha',
            field=models.DateField(blank=True, help_text='Fecha hasta la cual aplicar esta disponibilidad (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes')]),
        ),
    ]
