# Generated by Django 4.2.27 on 2026-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_alter_coordinados_ack_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaReintentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_id', models.IntegerField(db_index=True, help_text='ID del turno que no pudo coordinarse', verbose_name='ID Turno')),
                ('mensaje_hl7', models.TextField(help_text='Mensaje OML^O21 completo en formato ER7 (para reenvío)', verbose_name='Mensaje HL7')),
                ('intentos', models.IntegerField(default=0, help_text='Cantidad de intentos de envío realizados', verbose_name='Intentos')),
                ('ultimo_error', models.TextField(blank=True, default='', help_text='Descripción del último error al intentar enviar', verbose_name='Último error')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Momento en que se registró el fallo inicial', verbose_name='Fecha de creación')),
                ('fecha_ultimo_intento', models.DateTimeField(blank=True, help_text='Momento del último intento de reenvío', null=True, verbose_name='Último intento')),
            ],
            options={
                'verbose_name': 'Mensaje HL7 en cola',
                'verbose_name_plural': 'Cola de reintentos HL7',
                'db_table': 'turnos_cola_reintentos',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
