# Generated by Django 4.2.27 on 2026-05-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_agregar_cola_reintentos_hl7'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinados',
            name='orden_estado',
            field=models.CharField(blank=True, default='', help_text='Estado de la orden según ORL^O22: UA/IP/CM/SC', max_length=5),
        ),
        migrations.AddField(
            model_name='coordinados',
            name='orl_recibido',
            field=models.TextField(blank=True, default='', help_text='Mensaje ORL^O22 completo recibido del LIS'),
        ),
    ]
