# Generated by Django 5.2.9 on 2025-12-04 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_weeklyavailability_desde_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde_fecha', models.DateField(help_text='Fecha de inicio del rango')),
                ('hasta_fecha', models.DateField(help_text='Fecha de fin del rango')),
                ('cantidad', models.PositiveIntegerField(default=5, help_text='Cantidad de cupos para cada día de lunes a viernes')),
                ('aplicado', models.BooleanField(default=False, help_text='Si está aplicado, los cupos ya fueron creados')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_mensuales', to='turnos.agenda')),
            ],
            options={
                'verbose_name': 'Turno Mensual',
                'verbose_name_plural': 'Turnos Mensuales',
                'ordering': ['-creado'],
            },
        ),
    ]
