# Generated by Django 4.2.27 on 2026-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_agregar_campos_orl'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinados',
            name='numero_protocolo_lis',
            field=models.CharField(blank=True, default='', help_text='Filler Order Number asignado por el LIS (Navify) en el ORU^R01', max_length=100, verbose_name='Número de protocolo LIS'),
        ),
        migrations.AddField(
            model_name='coordinados',
            name='oru_recibido',
            field=models.TextField(blank=True, default='', help_text='Mensaje ORU^R01 completo recibido del LIS (resultado de laboratorio)', verbose_name='ORU recibido'),
        ),
    ]
