# Generated by Django 5.2.9 on 2025-12-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_coordinados'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='apellido',
            field=models.CharField(default='', max_length=200),
        ),
    ]
