# Generated by Django 4.2.27 on 2026-05-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_add_ordenes_m2m'),
        ('turnos', '0010_agregar_campos_oru_coordinados'),
    ]

    operations = [
    ]
