# Generated by Django 4.2.27 on 2026-06-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_merge_20260528_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinados',
            name='estado_informe',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('CON_RESULTADOS', 'Con Resultados'), ('FINALIZADO', 'Finalizado')], db_index=True, default='', help_text='Estado del informe PDF generado por Navify', max_length=20, verbose_name='Estado del Informe PDF'),
        ),
        migrations.AddField(
            model_name='coordinados',
            name='nombre_archivo_pdf',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Nombre del archivo PDF generado por Navify (ej: Ambulatorio_12345678_98765_T001.pdf)', max_length=255, verbose_name='Nombre del archivo PDF'),
        ),
        migrations.AddField(
            model_name='coordinados',
            name='ruta_archivo_pdf',
            field=models.CharField(blank=True, default='', help_text='Ruta relativa del archivo para ser servido desde la UI', max_length=512, verbose_name='Ruta del archivo PDF'),
        ),
        migrations.AlterField(
            model_name='coordinados',
            name='numero_protocolo_lis',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Filler Order Number asignado por el LIS (Navify) en el ORU^R01', max_length=100, verbose_name='Número de protocolo LIS'),
        ),
        migrations.AddIndex(
            model_name='coordinados',
            index=models.Index(fields=['nombre_archivo_pdf'], name='turnos_coor_nombre__983ce0_idx'),
        ),
    ]
