# Generated by Django 5.2.9 on 2025-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_turno_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='medico',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
