# Generated by Django 5.2.9 on 2025-12-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0012_turno_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='nota_interna',
            field=models.TextField(blank=True, default=''),
        ),
    ]
