# Generated by Django 5.2.9 on 2025-12-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0013_turno_nota_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='capacidaddia',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='coordinados',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cupo',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='turno',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='turnomensual',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='weeklyavailability',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
