# Generated by Django 4.2.27 on 2026-01-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0014_agenda_usuario_capacidaddia_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='turnomensual',
            name='agenda',
        ),
        migrations.AlterUniqueTogether(
            name='weeklyavailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='weeklyavailability',
            name='agenda',
        ),
        migrations.DeleteModel(
            name='CapacidadDia',
        ),
        migrations.DeleteModel(
            name='TurnoMensual',
        ),
        migrations.DeleteModel(
            name='WeeklyAvailability',
        ),
    ]
