# Generated by Django 4.2.27 on 2026-01-24 22:05

from django.db import migrations, models
import django.db.models.deletion


def cleanup_orphaned_turnos(apps, schema_editor):
    """Elimina turnos que referencian pacientes que no existen."""
    from django.db import connection
    
    # Usar SQL directo para limpiar huérfanos
    with connection.cursor() as cursor:
        # dni es VARCHAR, necesita conversión a INT
        cursor.execute("""
            SELECT t.id FROM turnos_turno t
            WHERE t.dni IS NOT NULL 
            AND t.dni ~ '^[0-9]+$'
            AND NOT EXISTS (SELECT 1 FROM pacientes_paciente p WHERE p.id = t.dni::BIGINT)
        """)
        orphaned_ids = [row[0] for row in cursor.fetchall()]
        
        if orphaned_ids:
            print(f"Eliminando {len(orphaned_ids)} turnos huérfanos...")
            # Eliminar los huérfanos
            placeholders = ','.join(['%s'] * len(orphaned_ids))
            cursor.execute(f"DELETE FROM turnos_turno WHERE id IN ({placeholders})", orphaned_ids)
            print(f"✅ Se eliminaron {len(orphaned_ids)} turnos huérfanos")
        else:
            print("✅ No hay turnos huérfanos para eliminar")


def reverse_cleanup(apps, schema_editor):
    """No se puede revertir - esta migración limpia datos."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('turnos', '0016_medico_fk'),
    ]

    operations = [
        migrations.RunPython(cleanup_orphaned_turnos, reverse_cleanup),
        migrations.RemoveField(
            model_name='turno',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='turno',
            name='dni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='pacientes.paciente'),
        ),
    ]
