# Generated by Django 4.2.27 on 2026-01-24 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('turnos', '0017_remove_turno_apellido_remove_turno_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinados',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='coordinados',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='coordinados',
            name='dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente', verbose_name='Paciente'),
        ),
    ]
