# Generated by Django 4.2.27 on 2026-01-25 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos', '0019_migrate_usuario_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to=settings.AUTH_USER_MODEL),
        ),
    ]
