# Generated by Django 4.2.27 on 2026-04-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la institucion de origen', max_length=200, unique=True, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, help_text='Desmarcar para desactivar sin eliminar', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Institucion',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['nombre'],
            },
        ),
    ]
