# Generated by Django 4.2.27 on 2026-04-30 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_alter_agenda_options_alter_cupo_options_and_more'),
        ('ordenes', '0004_add_determinaciones_complejas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenlaboratorio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TURNO', 'Turno Asignado'), ('INGRESADA', 'Ingresada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenlaboratorio',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden', to='turnos.turno'),
        ),
    ]
