# Generated by Django 4.2.27 on 2026-05-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_agregar_estado_turno_y_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenlaboratorio',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='ordenlaboratorio',
            name='tipo_origen',
            field=models.CharField(choices=[('AMBULATORIO', 'Ambulatorio'), ('GUARDIA', 'Guardia'), ('INTERNACION', 'Internación'), ('ORDENES_PROGRAMADAS', 'Órdenes Programadas')], max_length=20),
        ),
    ]
