# Generated by Django 4.2.27 on 2026-05-30 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0006_add_fecha_programada_origen_programada'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinadosOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_coordinacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de coordinación')),
                ('determinaciones', models.TextField(blank=True, help_text='Códigos de determinaciones enviadas separados por coma', verbose_name='Determinaciones (CSV)')),
                ('mensaje_tipo', models.CharField(choices=[('ASTM', 'ASTM (legacy)'), ('HL7', 'HL7 v2.5')], default='HL7', help_text='HL7 o ASTM según el protocolo utilizado', max_length=10, verbose_name='Tipo de mensaje')),
                ('mensaje_hl7', models.TextField(blank=True, verbose_name='Mensaje HL7 enviado')),
                ('ack_recibido', models.TextField(blank=True, verbose_name='ACK recibido del LIS')),
                ('ack_estado', models.CharField(blank=True, choices=[('AA', 'Aceptado'), ('AE', 'Error'), ('AR', 'Rechazado')], help_text='AA=aceptado, AE=error, AR=rechazado', max_length=10, verbose_name='Estado del ACK')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinaciones', to='ordenes.ordenlaboratorio', verbose_name='Orden de laboratorio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario coordinador')),
            ],
            options={
                'verbose_name': 'Coordinación de orden',
                'verbose_name_plural': 'Coordinaciones de órdenes',
                'ordering': ['-fecha_coordinacion'],
                'indexes': [models.Index(fields=['orden'], name='ordenes_coo_orden_i_838d59_idx'), models.Index(fields=['-fecha_coordinacion'], name='ordenes_coo_fecha_c_208fbc_idx'), models.Index(fields=['mensaje_tipo'], name='ordenes_coo_mensaje_c66ffb_idx')],
            },
        ),
    ]
