# Generated by Django 4.2.27 on 2026-06-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_add_coordinados_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinadosorden',
            name='estado_informe',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('CON_RESULTADOS', 'Con Resultados'), ('FINALIZADO', 'Finalizado')], db_index=True, default='', help_text='Estado del informe PDF generado por Navify', max_length=20, verbose_name='Estado del Informe PDF'),
        ),
        migrations.AddField(
            model_name='coordinadosorden',
            name='nombre_archivo_pdf',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Nombre del archivo PDF generado por Navify', max_length=255, verbose_name='Nombre del archivo PDF'),
        ),
        migrations.AddField(
            model_name='coordinadosorden',
            name='numero_protocolo_lis',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Filler Order Number asignado por el LIS (Navify) en el ORU^R01', max_length=100, verbose_name='Número de protocolo LIS'),
        ),
        migrations.AddField(
            model_name='coordinadosorden',
            name='ruta_archivo_pdf',
            field=models.CharField(blank=True, default='', help_text='Ruta relativa del archivo para ser servido desde la UI', max_length=512, verbose_name='Ruta del archivo PDF'),
        ),
        migrations.AddIndex(
            model_name='coordinadosorden',
            index=models.Index(fields=['nombre_archivo_pdf'], name='ordenes_coo_nombre__632600_idx'),
        ),
    ]
