# Generated by Django 4.2.27 on 2026-01-21 21:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Determinacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('visible', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDeterminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('determinaciones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=list, help_text='Códigos de determinaciones incluidas en el perfil', size=None)),
            ],
        ),
    ]
