# Generated by Django 4.2.27 on 2026-01-29 00:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('determinaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeterminacionCompleja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('tiempo', models.IntegerField(default=3)),
                ('nombre', models.CharField(default='Perfil de determinación', help_text='Nombre descriptivo del perfil del perfil', max_length=50)),
                ('determinaciones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=list, help_text='Códigos de determinaciones Complejas', size=None)),
                ('visible', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='determinacion',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='determinacion',
            name='tiempo',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='perfildeterminacion',
            name='nombre',
            field=models.CharField(default='Perfil de determinación', help_text='Nombre descriptivo del perfil del perfil', max_length=50),
        ),
    ]
