# Generated by Django 4.2.27 on 2026-01-22 21:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('determinaciones', '0002_determinacion_tiempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeterminacionCompleja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('determinaciones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=list, help_text='Códigos de determinaciones Complejas', size=None)),
            ],
        ),
    ]
