# Generated by Django 4.2.27 on 2026-04-24 18:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('determinaciones', '0002_determinacioncompleja_determinacion_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del sector del laboratorio', max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='determinacion',
            options={'ordering': ['codigo'], 'verbose_name': 'Determinación', 'verbose_name_plural': 'Determinaciones'},
        ),
        migrations.AlterModelOptions(
            name='determinacioncompleja',
            options={'ordering': ['codigo'], 'verbose_name': 'Determinación Compleja', 'verbose_name_plural': 'Determinaciones Complejas'},
        ),
        migrations.AlterModelOptions(
            name='perfildeterminacion',
            options={'ordering': ['codigo'], 'verbose_name': 'Perfil de Determinación', 'verbose_name_plural': 'Perfiles de Determinación'},
        ),
        migrations.AddField(
            model_name='determinacion',
            name='guardia',
            field=models.BooleanField(default=False, help_text='Indica si esta determinación está disponible para órdenes de Guardia', verbose_name='Guardia'),
        ),
        migrations.AddField(
            model_name='determinacioncompleja',
            name='guardia',
            field=models.BooleanField(default=False, help_text='Indica si esta determinación está disponible para órdenes de Guardia', verbose_name='Guardia'),
        ),
        migrations.AlterField(
            model_name='determinacion',
            name='activa',
            field=models.BooleanField(default=True, help_text='Determina si la determinación está activa', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='determinacion',
            name='codigo',
            field=models.CharField(help_text='Código único de la determinación', max_length=4, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='determinacion',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo de la determinación', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='determinacion',
            name='stock',
            field=models.BooleanField(default=True, help_text='Indica si hay stock disponible para esta determinación', verbose_name='Stock Disponible'),
        ),
        migrations.AlterField(
            model_name='determinacion',
            name='tiempo',
            field=models.PositiveIntegerField(default=3, help_text='Tiempo de entrega en días', verbose_name='Tiempo de Entrega'),
        ),
        migrations.AlterField(
            model_name='determinacion',
            name='visible',
            field=models.BooleanField(default=True, help_text='Determina si la determinación es visible en el sistema', verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='determinacioncompleja',
            name='activa',
            field=models.BooleanField(default=True, help_text='Determina si la determinación está activa', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='determinacioncompleja',
            name='codigo',
            field=models.CharField(help_text='Código único de la determinación compleja', max_length=4, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='determinacioncompleja',
            name='determinaciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=list, help_text='Códigos de determinaciones complejas incluidas', size=None, verbose_name='Determinaciones'),
        ),
        migrations.AlterField(
            model_name='determinacioncompleja',
            name='nombre',
            field=models.CharField(default='Determinación Compleja', help_text='Nombre descriptivo de la determinación compleja', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='determinacioncompleja',
            name='stock',
            field=models.BooleanField(default=True, help_text='Indica si hay stock disponible para esta determinación', verbose_name='Stock Disponible'),
        ),
        migrations.AlterField(
            model_name='determinacioncompleja',
            name='tiempo',
            field=models.PositiveIntegerField(default=3, help_text='Tiempo de entrega en días', verbose_name='Tiempo de Entrega'),
        ),
        migrations.AlterField(
            model_name='determinacioncompleja',
            name='visible',
            field=models.BooleanField(default=True, help_text='Determina si la determinación es visible en el sistema', verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='perfildeterminacion',
            name='codigo',
            field=models.CharField(help_text='Código único del perfil', max_length=4, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='perfildeterminacion',
            name='determinaciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), default=list, help_text='Códigos de determinaciones incluidas en el perfil', size=None, verbose_name='Determinaciones'),
        ),
        migrations.AlterField(
            model_name='perfildeterminacion',
            name='nombre',
            field=models.CharField(default='Perfil de determinación', help_text='Nombre descriptivo del perfil de determinación', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='determinacion',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Sector del laboratorio al que pertenece esta determinación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='determinaciones', to='determinaciones.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='determinacioncompleja',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Sector del laboratorio al que pertenece esta determinación compleja', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='determinaciones_complejas', to='determinaciones.sector', verbose_name='Sector'),
        ),
    ]
