# Generated by Django 4.2.27 on 2026-01-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('determinaciones', '0003_determinacioncompleja'),
    ]

    operations = [
        migrations.AddField(
            model_name='determinacioncompleja',
            name='nombre',
            field=models.CharField(default='Perfil de determinación', help_text='Nombre descriptivo del perfil del perfil', max_length=50),
        ),
        migrations.AddField(
            model_name='perfildeterminacion',
            name='nombre',
            field=models.CharField(default='Perfil de determinación', help_text='Nombre descriptivo del perfil del perfil', max_length=50),
        ),
    ]
