# Generated by Django 4.2.27 on 2026-05-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('determinaciones', '0003_alter_determinacion_options_and_more'),
        ('determinaciones', '0004_sectores_y_asignaciones'),
    ]

    operations = [
    ]
