# Generated by Django 4.2.27 on 2026-01-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('determinaciones', '0004_determinacioncompleja_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='determinacioncompleja',
            name='tiempo',
            field=models.IntegerField(default=3),
        ),
    ]
