# Generated by Django 4.2.27 on 2026-01-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('determinaciones', '0005_determinacioncompleja_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='determinacion',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='determinacioncompleja',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='determinacioncompleja',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='determinacioncompleja',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
